apiVersion: apps/v1
kind: Deployment
metadata:
  name: machinelearning-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: machinelearning
  template:
    metadata:
      labels:
        app: machinelearning
    spec:
      containers:
        - name: machinelearning
          image: ghrc.io/lab2-ds3/sduquec/mlmodel-app:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: machinelearning-service
spec:
  selector:
    app: machinelearning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
